
services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql_db_tabd
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root          
      MYSQL_DATABASE: crm                
      MYSQL_USER: admin                  
      MYSQL_PASSWORD: admin              
    ports:
      - "3307:3306"                      
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: